# mktxp's own runtime settings (it requires this file to exist).
[MKTXP]
    listen = '0.0.0.0:49090'
    socket_timeout = 5
    initial_delay_on_failure = 120
    max_delay_on_failure = 900
    delay_inc_div = 5
    bandwidth = False
    verbose_mode = False
